apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: gcr.io/cloud-builders/gcloud
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
